swagger: "2.0"
info:
  version: "1.0.0"
  title: "Refatorando em Microsservices"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "acme-producer.api.io"
basePath: "/v1"
tags:
- name: "Clientes"
  description: "API cliente domain"
- name: "Instalacoes"
  description: "API instalacao domain"
- name: "Faturas"
  description: "API fatura domain"
schemes:
- "https"
- "http"
paths:
  /clientes:
    post:
      tags:
      - "Clientes"
      summary: "Criar cliente na base"
      operationId: "inserirCliente"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/Cliente"
      responses:
        "201":
          description: "cliente criado com sucesso"
      security:
        - apiKey: []
    get:
      tags:
      - "Clientes"
      summary: "Recupera info de todos os clientes"
      description: ""
      operationId: "getAllClienteData"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/DadosClientesCadastrados"
        "400":
          description: "Invalid cpf supplied"
        "404":
          description: "User not found"
      security:
        - apiKey: []
  /clientes/{cpf}:
    get:
      tags:
      - "Clientes"
      summary: "Recupera info por CPF"
      description: ""
      operationId: "getClienteById"
      produces:
      - "application/json"
      parameters:
      - name: "cpf"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/DadosCliente"
        "400":
          description: "Invalid cpf supplied"
        "404":
          description: "User not found"
      security:
        - apiKey: []

  /instalacoes:
    post:
      tags:
      - "Instalacoes"
      summary: "Criar instalacao na base"
      operationId: "inserirInstalacao"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/Instalacao"
      responses:
        "201":
          description: "instalacao criada com sucesso"
      security:
        - apiKey: []
    get:
      tags:
      - "Instalacoes"
      summary: "Recupera todas as instalacoes"
      description: ""
      operationId: "getAllInstalacao"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/DadosInstalacaoCadastrados"
        "400":
          description: "Some error"
        "404":
          description: "Instalacao nao encontrada"
      security:
        - apiKey: []
  /instalacoes/{id}:
    get:
      tags:
      - "Instalacoes"
      summary: "Recupera info por ID"
      description: ""
      operationId: "getInstalacaoById"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/DadosInstalacao"
        "400":
          description: "Invalid id supplied"
        "404":
          description: "Instalacao nao encontrada"
      security:
        - apiKey: []
        
  /instalacoes/cliente/{cpf}:
    get:
      tags:
      - "Instalacoes"
      summary: "Recupera info por CPF"
      description: ""
      operationId: "getInstalacaoByCpf"
      produces:
      - "application/json"
      parameters:
      - name: "cpf"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/DadosInstalacao"
        "400":
          description: "Invalid id supplied"
        "404":
          description: "Instalacao nao encontrada"
      security:
        - apiKey: []
        
  /faturas:
    post:
      tags:
      - "Faturas"
      summary: "Criar Faturas na base"
      operationId: "inserirFatura"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/Fatura"
      responses:
        "201":
          description: "Faturas criada com sucesso"
      security:
        - apiKey: []
    get:
      tags:
      - "Faturas"
      summary: "Recupera todas as Faturas"
      description: ""
      operationId: "getAllFatura"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/DadosFaturasCadastradas"
        "400":
          description: "Some error"
        "404":
          description: "Instalacao nao encontrada"
      security:
        - apiKey: []
  /faturas/{id}:
    get:
      tags:
      - "Faturas"
      summary: "Recupera info por ID"
      description: ""
      operationId: "getFaturaById"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/DadosFatura"
        "400":
          description: "Invalid id supplied"
        "404":
          description: "Fatura nao encontrada"
      security:
        - apiKey: []
  /faturas/cliente/{cpf}:
    get:
      tags:
      - "Faturas"
      summary: "Recupera info por CPF"
      description: ""
      operationId: "getFaturasByCpf"
      produces:
      - "application/json"
      parameters:
      - name: "cpf"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/DadosFatura"
        "400":
          description: "Invalid id supplied"
        "404":
          description: "Instalacao nao encontrada"
      security:
        - apiKey: []
securityDefinitions:
  apiKey:
    type: apiKey
    in: header
    name: X-API-Key
    
definitions:
  DadosClientesCadastrados:
    type: "object"
    properties:
      dados:
        type: "array"
        items:
          $ref: "#/definitions/DadosCliente"
  DadosCliente:
    type: "object"
    properties:
      dadosCliente:
        $ref: "#/definitions/Cliente"
      dadosInstalacao:
        $ref: "#/definitions/DadosInstalacao"
  Cliente:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      nome:
        type: "string"
      dataNascimento:
        type: "string"
        format: "date"
      cpf:
        type: "string"
      endereco:
        $ref: "#/definitions/Endereco"
    xml:
      name: "Cliente"
  DadosInstalacaoCadastrados:
    type: "object"
    properties:
      dados:
        type: "array"
        items:
          $ref: "#/definitions/DadosInstalacao"
  DadosInstalacao:
    type: "object"
    properties:
      id:
        type: "string"
      endereco:
        $ref: "#/definitions/Endereco"
  Instalacao:
    type: "object"
    properties:
      endereco:
          $ref: "#/definitions/Endereco"
          
  DadosFaturasCadastradas:
    type: "object"
    properties:
      dados:
        type: "array"
        items:
          $ref: "#/definitions/DadosFatura"
  DadosFatura:
    type: "object"
    properties: 
      id:
        type: "integer"
      dadosFatura:
        $ref: "#/definitions/Fatura"
        
  Fatura:
    type: "object"
    properties:
      codigoInstalacao:
        type: "string"
      cpf:
        type: "string"
      dataVencimento:
        type: "string"
        format: "date"
      dataLeitura:
        type: "string"
        format: "date"
      valorLeitura:
        type: "number"
      valorConta:
        type: "number"
          
  Endereco:
    type: "object"
    properties:
      logradouro:
        type: "string"
      cep:
        type: "string"
      complemento:
        type: "string"